import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";


export default function Home() {
  return (
    <>
      <Head>
        <title>E-commerce site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>

      <div className="flex justify-center my-10">
        <Image src="/home.jpg" alt="f" width={700} height={10} />
      </div>
    </>
  );
}
